# -*- coding: utf-8 -*-
"""Day2_Question1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hjoWF9BirHqJkhAV4NTH9hZ6S0SJ3Kfa
"""

# Creating an arbitrary list with range function (it works for only range(n) is defined for even n)
my_list2 = list(range(8))
print("Created list:", my_list2)
#Describing the index for dividing index into two part
length = len(my_list2)
print("Length of the list:", length)

middle_index = length//2
print(middle_index)

# Getting first and second half separately
first_part_list = my_list2[:middle_index]
print("First half of the list: ", first_part_list)
second_part_list = my_list2[middle_index:]
print("Second half of the list: ", second_part_list)

#Swapping the list 
swapped_list = second_part_list + first_part_list
print("Swapped list is: ", swapped_list)