# -*- coding: utf-8 -*-
"""HW5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bAHiWi4TYpeXGK2KhJgBp093u0Lp17aC
"""

# Creating three classes 

class Animals:
    def __init__(self, Name, Type, lifetime):
        self.name = Name
        self.type_animal = Type
        self.lifetime_animal = lifetime
    
    def print_info(self):
        print(self.name + " from " + self.type_animal, 
              "family and they have average lifetime as", 
              self.lifetime_animal, "years")

class Dog(Animals):
    pass

print(dog)
dog = Dog("Dogs", "canidae", "13")
dog.print_info()

class Cat(Animals):
    pass

cat = Cat("Cats", "Felidae", "16")
cat.print_info()

# Create Dogs and Cats as other classes with inheritence also
class Dogs(Animals):
    def __init__(self, Variety, Color):
        self.variety = Variety
        self.color = Color

dog = Dogs("Golden", "Gold yellow")
dog.name = "Dog"
dog.type_animal = "Retriever"
dog.lifetime_animal= "12"

class Dogs:
    def __init__(self, Name, lifetime, Variety, Color):
        self.name = Name
        self.lifetime = lifetime
        self.variety = Variety
        self.color = Color
    
    def print_color(self):
        print(self.name + " has " + self.color + " color")
    
    def print_lifetime(self):
        print(self.variety + " lives " + self.lifetime + " years in average")
    
    def print_dog_info(self):
        print(self.variety  + " lives " + self.lifetime + 
              " in average and " + self.name, " has " + self.color)

golden = Dogs("Pupa", "12", "Retriever", "golden yellow")
golden.print_color()
golden.print_lifetime()
golden.print_dog_info()

class Cats(Dogs):
    def __init__(self, nationality, scientificname):
        self.nation = nationality
        self.scientificname = scientificname
    
    def print_cat_status(self):
        print(self.name + " is a cat and has scientific name as " + self.scientificname + " and comes from " + self.nation)

sansli = Cats("Iran", "Felis catus")
sansli.name = "Sansli"

sansli.print_cat_status()