# -*- coding: utf-8 -*-
"""Final Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18nhXXw77PrP87URpV2xpz4pZXe7hdjo7
"""

# Simple Company Management System
# Creating class for employees
class employees:

  def __init__(self, names, ages, languages):

    self.name = names
    self.age = ages
    self.language = languages

  def print_info(self):
    print("{} is {} years old".format(self.name, self.age))
    print("and one of the " + type(self).__name__ + 
          ", can speak the languages: " + self.language)

#Creating class for employees with inheritence

class manager(employees):
  pass

# Information about employees
employee1 = employees("Mark", "24", "English")
employee2 = employees("Ozan", "33", "Turkish, English")

#Information about the manager
manager1 = manager("John", "45", "English, Spanish")

#Printing the languages of employees and manager
employee1.print_info()
employee2.print_info()

manager1.print_info()